### ISSUE TITLE
Move commands into seperate files

### ISSUE THREAD

**Issue by supergrecko** [jbis9051/JSProgrammingDiscordBot#3]
I think it's really messy to have almost every command stored inside a single file. Creating a directory named commands and separating each command into its own file inside that directory will clean up a lot.

**Comment by scitronboy** [comment]
Maybe we could have related commands in the same file?

**Comment by jbis9051** [comment]
@supergrecko I will be changing over to a dynamic command registration system soon. Each command (or related commands) will be in the plugin folder each with separate files

**Comment by jbis9051** [comment]
@supergrecko  Check code. I think you will be happy.
