### ISSUE TITLE
Bot crashes if "Bot-fun" does not exist

### ISSUE THREAD

**Issue by supergrecko** [jbis9051/JSProgrammingDiscordBot#5]
If a server does not have the channel named #bot-fun the process will crash.

**Comment by scitronboy** [comment]
I suggest using a command to set the default bot server IF the bot-fun or bot-commands channel doesn't exist; like `!! set-bot-channel #bot-stuff`

**Comment by jbis9051** [comment]
Gonna combine both ideas at add it config
